name: TestPlugin
version: '${project.version}'
main: io.github.zepelown.testplugin.TestPlugin
api-version: 1.19
commands:
  thelp:
    description: help command
    aliases:
      - thelp2
  tgivedia:
    description: givedia
  topeninv:
    description: open gui
  tgetpotion:
    description: get custom potion
